spring.application.name=CarRental
spring.port = 8080
spring.datasource.platform= mysql
spring.datasource.url = jdbc:mysql://localHost:3306/carrental
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username= saiganesh
spring.datasource.password=9030696681
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
